sudo: false

language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    secure: xE4epwGRaSy7FlkjckXvyApeWqtRtKxQOAlLpNGgXe2ba7tBRGZCXvAVyrlr0jcV1shWhR89K3/kPCGHyR/gdBiQzyZgREdE08bdkq6x+i+Hk3hIgH3CickhMT7ls3C0NDoZiTN46MPRYJNhmKjahpHk5DiyEGE86D9w0/lUfbw=

before_script:
  - composer install --dev --prefer-source

script:
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - ./vendor/bin/test-reporter
